---
title: "SDS 291 Data Appendix"
author: "Isabel Gomez, Ester Zhao, Karina Lieb"
date: "March 20, 2019"
output: html_document
---

```{r}
#Load packages
# knitr settings to control how R chunks work and how the pdf is compiled when knit.
# install.packages("readr")
library(readr)
library(knitr)
require(knitr)
opts_chunk$set(
  tidy=TRUE,                     # display code as typed
  size="small",                   # slightly smaller font for code
  tidy.opts=list(width.cutoff=65), # wrap text and long comments
  fig.width=7, fig.height=5           #figure size
)
require(mosaic)
require(magrittr)
require(tidyverse)
```

###Data wrangling
```{r}
#First load ipums
library(ipumsr)

# Note that you can pass in the loaded DDI into the library(read_ipums_micro()`
nhis_ddi <- read_ipums_ddi("nhis_00002.xml")

nhis_data <- read_ipums_micro(nhis_ddi, verbose = FALSE)
View(nhis_data)

#Finding the variables that have a label
nhis_data %>%
  select_if(is.labelled)

# Convert the labels to factors (and drop the unused levels) and filter for only 2017
nhis_data<-nhis_data%>%
  mutate(FSRAWSCORE = droplevels(as_factor(FSRAWSCORE)),
         REGION = droplevels(as_factor(REGION)),
         RACE = droplevels(as_factor(RACEBR)))

#Filter for only 2017
nhis_data <- nhis_data %>%
  filter(YEAR == 2017)

```

```{r}
#Filter GOTSTAMPFAM to only include those who answered "Yes" Filter for those only who received SNAP benefits

#GOTSTAMPFAM Codes: 10 = NO, 21 = Yes in last calendar year, 22 = Yes in last month.
#This will remove all observations where GOTSTAMPFAM does not equal 21 or 22
nhis_data<-nhis_data %>%
  filter(GOTSTAMPFAM==21 | GOTSTAMPFAM==22)

```


```{r}
#Convert FSRAWSCORE into a categorical variable, called FoodSecurity, with 3 levels: Secure (0-2), Low Food Security(3-5), Very Low Food Security (6-10). 

#FSRAWSCORE Codes: 

nhis_data<- nhis_data %>%
  mutate(FOOD_SECURITY = if_else(FSRAWSCORE %in% c(0,1,2), "Secure",
                            if_else(FSRAWSCORE %in% c(3,4,5), "Low Food Security ", 
                                    "Very Low Food Security")))
```


```{r}
#Mutate METRO to be a binary indicator variable called URBAN that will have a 1 if a househould if the household is located in urban area and is 0 otherwise. Combine "not in Central City and MSA" and "in Central City" to be categorized as urban (1) and "not in MSA" to be categorized as rural (0) ##SHOULD WE REMOVE THIS

#METRO Codes: 010 = MSA In Central City, 020 = MSM Not in Central City. All else are non-urban locations. 
nhis_data<-nhis_data %>%
  mutate(URBAN=if_else(METRO %in% c(010, 020), 1, 0))
```


```{r}
#---------- WRANGLE CONFOUNDING VARIABLES -------------

#REGION: a categorical variable with string labels as values.

#AGE: A numerical variable indicating age of the individual surveyed.

#EDUC: Create a categorical variable EDUCATION, with three levels. Did not graduate high school (0), high school graduate or GED (1), vocational degree (2), bachelor's degree/higher (3).
nhis_data<-nhis_data %>%
  mutate(EDUCATION=if_else(EDUC %in% c(500, 601, 602, 603), 3, #bachelor's or higher
                           if_else(EDUC %in% c(402, 403), 2, #vocational degree
                                   if_else(EDUC %in% c(301, 302, 401), 1, 0)))) #high school or GED. Includes college drop outs.
                                  #else, set to 0 (did not complete high school)
  



#RACE: Has been set to labels. Filter out those who chose not to answer race.
nhis_data<-nhis_data %>%
  filter(RACE != "Unknown-refused" | RACE != "Unknown-not ascertained" | RACE != "Unknown-don't know") 
  
  
  #INCOME: Make into a categorical variable. Low-Income includes any family making $0 - $49,999, Middle-Income includes any family making $50,000 - $99,999. High-Income families include any family make more than $100,000
nhis_data<-nhis_data %>%
  mutate(FAM_INCOME=if_else(INCFAM07ON %in% c(10,11,12), "Low Income",
                            if_else(INCFAM07ON %in% c(21,22,23), "Middle Income",
                                    if_else(INCFAM07ON %in% c(96,99), "N/A", "High Income"))))

#For Income, do we want remove the undefined and unknown, re-labelled as N/A. 

  #HEALTH: Make into a binary inducator variable Health_Issues, which has a value of (0) if the individual is healthy (Code 1-3), and a value of (1) if the individual has fair to poor health (Code 4-5). Give a patch fix value of (2) to all other values for now.
 nhis_data <- nhis_data %>% 
   mutate(Health_Issues=if_else(HEALTH %in% c(1,2,3), 0, #0 for healthy
                               if_else(HEALTH %in% c(4,5), 1, 2))) #1 for poor health, 2 for all else 
  
  #NCHILD: already contains total number of children. Cap at 9 total. The max amount of children in the data is 7. Could we also treat this as numeric.
 
  
  #FAMOLDNO: number of persons in the household aged 65 or older. Data collection cap at 5 total. The max amount elders in our data is just 3. 
  
  #NUMPREC: number of individuals in the household total. "A 3 digit numeric value". Should we categorize this or should we just keep this as numeric as well. How much does it matter the formatting of the confounding variables? 
 
 #GOTSTAMPFAM
  nhis_data <-   nhis_data %>% 
      mutate(RECEIVED_STAMPS = if_else(GOTSTAMPFAM %in% c(21,22,20), "Yes", "No"))
```

<!-- --------------------------------------------------- -->

#Structure and Names

```{r}
str(nhis_data, give.attr = FALSE)
```

#Select only the variables we'll need for analysis 
```{r}
nhis_data %>%
  select(AGE, FOOD_SECURITY, NCHILD, NUMPREC, FAMOLDNO, Health_Issues, RACE, EDUCATION, INCOME, REGION, RECEIVED_STAMPS)
```

